const _copyright = [
  "expert",
  "DLR",
  "DEX-școlar",
  "DRAM 2021",
  "DIN",
  "publicitate",
  "Șăineanu, ed. VI",
  "DEX-S",
  "DLRM",
  "DEX '75",
  "DGL",
  "DLRLC",
  "MDO",
  "Onomastic",
  "GER",
  "Etnobotanic",
  "GAER",
  "Sinonime82",
  "DMLR",
  "DELLR",
  "Enigmistică",
  "psi",
  "DELRIE",
  "DTLALL",
  "CADE",
  "DEI",
  "DLRA",
  "DFL",
  "DTM",
  "DE",
  "DA",
  "MEO",
  "DMG",
  "DRAM 2015",
  "D.Religios",
  "DGE",
  "DEXI",
  "MDTL",
  "Ortografic '01",
  "NODEX",
  "DOR",
  "Sinonime",
  "Ortografic",
  "Antonime",
  "DCR2",
  "GTA",
  "DSL",
  "Argou",
  "DS5",
  "MDN '00",
  "DFLR",
  "DAR",
  "DifSem",
  "DFS",
  "DGSSL",
  "CECC",
  "DELR",
  "Mitologic",
  "DLRC",
  "DLRLV",
  "DETS",
  "DAS",
  "DS",
  "DTL",
  "MDA",
  "DOOM 3",
  "MDA2",
  "DOOM 2",
  "Petro-Sedim",
  "Epitete",
  "DGS",
  "Scriban",
  "DEXLRA",
  "Legislație",
  "DAN",
  "MDN '08",
  "Șăineanu, ed. I",
  "DASLR",
  "DER",
];

/**
 * This is a list of dictionary identifiers that are under copyright, and cannot be queried without explicit permission.
 *
 * `dexonline-scraper` filters entries out from them by default, however this can be overriden in the case of
 * having obtained explicit permission for a given dictionary.
 *
 * Relevant link: https://dexonline.ro/licenta
 */
const copyright: readonly string[] = Object.freeze(_copyright);

export default copyright;
